spring:
#  datasource:
#    url: jdbc:tc:mysql:8.0.28:///reactivebooksdb
#    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
#    username: test
#    password: test
#    hikari:
#      poolName: Hikari
#      auto-commit: false
#      data-source-properties:
#        cachePrepStmts: true
#        prepStmtCacheSize: 250
#        prepStmtCacheSqlLimit: 2048
#        useServerPrepStmts: true

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    root: INFO
    org.hibernate: TRACE
