spring:
  datasource:
    url: jdbc:mysql://localhost:3306/reactivebooksdb?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: root
    password: ''
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  pattern:
    level: '%5p [${spring.zipkin.service.name:${spring.application.name:}},%X{traceId:-},%X{spanId:-}][%X{operation:-},%X{model:-},%X{user:-}]'
  level:
    root: INFO
    org:
      hibernate: INFO


